### ISSUE TITLE
break out the node-audio-element api

### ISSUE THREAD

**Issue by imsnif** [CommaSword/noise-generator#3]
This should be a different module. In my completely unbiased opinion, this is a much better way (though maybe not quite as lightweight!) as working with most node audio solutions out there right now (and it can also be used to spoon browser apps... kind of).

@amir-arad - do you want this as part CommaSword or shall I maintain it on my own?

**Comment by amir-arad** [comment]
anything you choose is fine

**Comment by imsnif** [comment]
Done https://github.com/CommaSword/node-mp3-player
